config/routes.rb
Rails.application.routes.draw do

  root to: "board#index"
  post "/", to: "board#create"
  get "/:board_id", to: "board#show", as: "board"
  post "/tickets", to: "tickets#create"
  put "/tickets", to: "tickets#update"

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :tickets, inverse_of: :board
  validates :title, presence: true
end

app/models/status.rb
class Status
  def self.names
    @names ||= ["Backlog", "Current Sprint", "In Progress", "Done"].map(&:freeze).freeze
  end

  def self.groups_for(tickets)
    grouped_by_name = names.map { |name| [name, []] }.to_h
    tickets.each { |ticket| grouped_by_name[ticket.status] << ticket }
    grouped_by_name.map { |name, tickets| [new(name, names), tickets] }.to_h
  end

  attr_accessor :name, :names

  def initialize(name, names)
    self.name  = name
    self.names = names
  end

  def has_prev?
    !index.zero?
  end

  def has_next?
    index < max_index
  end

  def prev_status
    names[index.pred] if has_prev?
  end

  def next_status
    names[index.succ] if has_next?
  end

  def display_name
    name
  end

  def css_id
    name.downcase.gsub(' ', '-')
  end

  private

  def index
    names.index name
  end

  def max_index
    names.length.pred
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_one :board, inverse_of: :tickets
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    board = Board.find_by(id: params[:board_id])
    @status_to_tickets = Status.groups_for(board.tickets)
  end

  def create
    board = Board.new(title: params[:Title])
    if board.save
      flash[:complete] = "Board created successfully"
    else
      flash[:alert] = "Board needs a title"
    end
    redirect_to root_path
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def create
    board = Board.find_by(id: Rails.application.routes.recognize_path(request.referrer)[:board_id])
    ticket = board.tickets.new(title: params[:Title], status: params[:status], description: params[:description])
    ticket.save

    redirect_to :back
  end

  def update
    ticket = Ticket.find_by(id: params[:format])
    ticket.update(status: params[:status])
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/board/index.html.erb
<div id="boards">
  <% @boards.each do |board| %>
    <%= link_to board.title, board_path(board) %>
  <% end %>
</div>

<br>
<div id="new-board">
  <form action="/" method="post" accept-charset="utf-8">
   <input type="text" placeholder="New Title" name="Title" id="Title"/>
   <p><input type="submit" value="Submit"></p>
 </form>
</div>

app/views/board/show.html.erb
<% @status_to_tickets.each do |status, tickets| %>
  <div id="<%= status.css_id %>">
    <h1><%= status.display_name %></h1>
    <% tickets.each do |ticket| %>
      <%= ticket.title %>
      <% if status.has_prev? %>
        <%= link_to "Move to #{status.prev_status}", tickets_path(ticket, status: status.prev_status), method: :put %>
      <% end %>

      <% if status.has_next? %>
        <%= link_to "Move to #{status.next_status}", tickets_path(ticket, status: status.next_status), method: :put %>
      <% end %>
    <% end %>
  </div>
<% end %>

<div id="new-ticket">
  <form action="/tickets" method="post" accept-charset="utf-8">
    <input type="text" placeholder="New Title" name="Title" id="Title"/>* required
    <br>
    <input type="text" placeholder="Optional Description" name="description" id="description"/>
    <br>
    Status:
    <select name="status">
      <option value="Backlog" selected="selected">Backlog</option>
      <option value="Current Sprint">Current Sprint</option>
      <option value="In Progress">In Progress</option>
      <option value="Done">Done</option>
    </select>

    <p><input type="submit" value="Submit"></p>
  </form>
</div>

app/views/dashboard/index.html.erb
<div id="boards">
  <% @boards.each do |board| %>
    <%= board.title %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeChallenge2</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash-#{name}", class: "text-center" %>
    <% end %>

    <%= yield %>

  </body>
</html>